module net.clanwolf.starmap.client {
	requires net.clanwolf.starmap.transfer;
	requires net.clanwolf.starmap.logging;
	requires net.clanwolf.starmap.client.preloader;
	requires jdk.crypto.ec;
	requires jdk.crypto.cryptoki;
	requires io.nadron.client;
	requires tektosyne;
	requires org.apache.commons.net;
	requires org.apache.commons.collections4;
	requires java.desktop;
	requires java.logging;
	requires javafx.graphics;
	requires javafx.controls;
	requires javafx.media;
	requires javafx.fxml;
	requires javafx.swing;
	requires irc.api;
	requires net.coobird.thumbnailator;
	requires com.github.kwhat.jnativehook;
	requires com.google.gson;
	requires java.sql;
	requires org.slf4j;

	opens net.clanwolf.starmap.client.security to javafx.fxml;
	opens net.clanwolf.starmap.client.gui to javafx.fxml;
	opens net.clanwolf.starmap.client.gui.panes to javafx.fxml;
	opens net.clanwolf.starmap.client.gui.panes.login to javafx.fxml;
	opens net.clanwolf.starmap.client.gui.panes.settings to javafx.fxml;
	opens net.clanwolf.starmap.client.gui.panes.rp to javafx.fxml;
	opens net.clanwolf.starmap.client.gui.panes.confirmAppClose to javafx.fxml;
	opens net.clanwolf.starmap.client.gui.panes.diplomacy to javafx.fxml;
	opens net.clanwolf.starmap.client.gui.panes.map to javafx.fxml;
	opens net.clanwolf.starmap.client.gui.panes.userinfo to javafx.fxml;
	opens net.clanwolf.starmap.client.gui.panes.chat to javafx.fxml;
	opens net.clanwolf.starmap.client.gui.panes.security to javafx.fxml;
	opens net.clanwolf.starmap.client.gui.panes.logging to javafx.fxml;
	opens net.clanwolf.starmap.client.mwo to com.google.gson;

	exports net.clanwolf.starmap.client.util;
	exports net.clanwolf.starmap.client.gui;
	exports net.clanwolf.starmap.client.gui.panes.login;
	exports net.clanwolf.starmap.client.gui.panes.settings;
	exports net.clanwolf.starmap.client.gui.panes.rp;
	exports net.clanwolf.starmap.client.gui.panes.confirmAppClose;
	exports net.clanwolf.starmap.client.gui.panes.map;
	exports net.clanwolf.starmap.client.gui.panes.userinfo;
	exports net.clanwolf.starmap.client.process.universe;
	exports net.clanwolf.starmap.client.action;
	exports net.clanwolf.starmap.client.security to javafx.fxml;
	exports net.clanwolf.starmap.client.gui.panes.security to javafx.fxml;
	exports net.clanwolf.starmap.client.gui.panes.chat to javafx.fxml;
	exports net.clanwolf.starmap.client.gui.panes.logging to javafx.fxml;
	exports net.clanwolf.starmap.client.gui.panes.dice to javafx.fxml;
	exports net.clanwolf.starmap.client.gui.panes.diplomacy to javafx.fxml;
	exports net.clanwolf.starmap.client.mwo;
}
