# open sftp://root:17E7OP%26Ec%24@82.165.244.122/ -hostkey="ssh-ed25519 255 3rYYeSUgq/rFCX8RhR+MXb7rumyu8+xOOEVsVlrDHLw=" -rawsettings FSProtocol=2
open sftp://root:pHcb5j9tVLGima7q@217.154.210.112/ -hostkey="ssh-ed25519 255 p/u7UxqxNZRs/DGcWo+6jE72PMfW3oqYLIUSbH1USIE" -rawsettings FSProtocol=2

rm /var/www/vhosts/clanwolf.net/c3.clanwolf.net/server/C3-IRCBot_shutdown.flag
rm /var/www/vhosts/clanwolf.net/c3.clanwolf.net/server/C3-TS3Bot_shutdown.flag
rm /var/www/vhosts/clanwolf.net/c3.clanwolf.net/server/C3-DiscordBot_shutdown.flag

exit
