@startuml
skinparam defaultTextAlignment center
skinparam rectangle {
  BackgroundColor<<optional>> beige
  BackgroundColor<<test>> lightGreen
  BackgroundColor<<runtime>> lightBlue
  BackgroundColor<<provided>> lightGray
}
rectangle "net.clanwolf.starmap\nnet.clanwolf.starmap.transfer\n7.4.3" as net_clanwolf_starmap_net_clanwolf_starmap_transfer_jar
rectangle "net.clanwolf.starmap\nnet.clanwolf.starmap.logging\n7.4.3" as net_clanwolf_starmap_net_clanwolf_starmap_logging_jar
rectangle "com.fasterxml.jackson.core\njackson-core\n2.15.2" as com_fasterxml_jackson_core_jackson_core_jar
rectangle "com.fasterxml.jackson.core\njackson-databind\n2.15.2" as com_fasterxml_jackson_core_jackson_databind_jar
rectangle "com.fasterxml.jackson.core\njackson-annotations\n2.15.2" as com_fasterxml_jackson_core_jackson_annotations_jar
rectangle "com.voodoodyne.jackson.jsog\njackson-jsog\n1.1.2" as com_voodoodyne_jackson_jsog_jackson_jsog_jar
rectangle "com.google.code.gson\ngson\n2.10.1" as com_google_code_gson_gson_jar
rectangle "net.clanwolf.starmap\nnet.clanwolf.starmap.client\n7.4.3" as net_clanwolf_starmap_net_clanwolf_starmap_client_jar
rectangle "net.clanwolf.starmap\nnet.clanwolf.starmap.client.preloader\n7.4.3" as net_clanwolf_starmap_net_clanwolf_starmap_client_preloader_jar
rectangle "org.openjfx\njavafx-graphics\n21" as org_openjfx_javafx_graphics_jar
rectangle "org.openjfx\njavafx-controls\n21" as org_openjfx_javafx_controls_jar
rectangle "net.clanwolf.starmap\nio.nadron.client\n7.4.3" as net_clanwolf_starmap_io_nadron_client_jar
rectangle "io.netty\nnetty-common\n4.1.94.Final" as io_netty_netty_common_jar
rectangle "io.netty\nnetty-transport\n4.1.94.Final" as io_netty_netty_transport_jar
rectangle "io.netty\nnetty-buffer\n4.1.94.Final" as io_netty_netty_buffer_jar
rectangle "io.netty\nnetty-resolver\n4.1.94.Final" as io_netty_netty_resolver_jar
rectangle "io.netty\nnetty-codec\n4.1.94.Final" as io_netty_netty_codec_jar
rectangle "io.netty\nnetty-handler\n4.1.94.Final" as io_netty_netty_handler_jar
rectangle "io.netty\nnetty-transport-native-unix-common\n4.1.94.Final" as io_netty_netty_transport_native_unix_common_jar
rectangle "org.openjfx\njavafx-controls\n21" as org_openjfx_javafx_controls_jar_win
rectangle "org.openjfx\njavafx-graphics\n21" as org_openjfx_javafx_graphics_jar_win
rectangle "org.openjfx\njavafx-base\n21" as org_openjfx_javafx_base_jar
rectangle "org.openjfx\njavafx-base\n21" as org_openjfx_javafx_base_jar_win
rectangle "org.openjfx\njavafx-fxml\n21" as org_openjfx_javafx_fxml_jar
rectangle "org.openjfx\njavafx-fxml\n21" as org_openjfx_javafx_fxml_jar_win
rectangle "org.openjfx\njavafx-web\n21" as org_openjfx_javafx_web_jar
rectangle "org.openjfx\njavafx-web\n21" as org_openjfx_javafx_web_jar_win
rectangle "org.openjfx\njavafx-media\n21" as org_openjfx_javafx_media_jar
rectangle "org.openjfx\njavafx-media\n21" as org_openjfx_javafx_media_jar_win
rectangle "org.openjfx\njavafx-swing\n21" as org_openjfx_javafx_swing_jar
rectangle "org.openjfx\njavafx-swing\n21" as org_openjfx_javafx_swing_jar_win
rectangle "org.kynosarges\ntektosyne\n6.2.0" as org_kynosarges_tektosyne_jar
rectangle "org.apache.commons\ncommons-collections4\n4.4" as org_apache_commons_commons_collections4_jar
rectangle "commons-net\ncommons-net\n3.9.0" as commons_net_commons_net_jar
rectangle "org.jetbrains\nannotations\n24.0.1" as org_jetbrains_annotations_jar
rectangle "org.jitsi\nirc-api\n1.0-0015-jitsi-1" as org_jitsi_irc_api_jar
rectangle "commons-codec\ncommons-codec\n1.15" as commons_codec_commons_codec_jar
rectangle "net.coobird\nthumbnailator\n0.4.20" as net_coobird_thumbnailator_jar
rectangle "com.github.kwhat\njnativehook\n2.2.2" as com_github_kwhat_jnativehook_jar
net_clanwolf_starmap_net_clanwolf_starmap_transfer_jar .[#D3D3D3].> net_clanwolf_starmap_net_clanwolf_starmap_logging_jar
net_clanwolf_starmap_net_clanwolf_starmap_transfer_jar -[#000000]-> com_fasterxml_jackson_core_jackson_core_jar
com_fasterxml_jackson_core_jackson_databind_jar .[#D3D3D3].> com_fasterxml_jackson_core_jackson_annotations_jar
com_fasterxml_jackson_core_jackson_databind_jar .[#D3D3D3].> com_fasterxml_jackson_core_jackson_core_jar
net_clanwolf_starmap_net_clanwolf_starmap_transfer_jar -[#000000]-> com_fasterxml_jackson_core_jackson_databind_jar
net_clanwolf_starmap_net_clanwolf_starmap_transfer_jar -[#000000]-> com_fasterxml_jackson_core_jackson_annotations_jar
net_clanwolf_starmap_net_clanwolf_starmap_transfer_jar -[#000000]-> com_voodoodyne_jackson_jsog_jackson_jsog_jar
net_clanwolf_starmap_net_clanwolf_starmap_transfer_jar -[#000000]-> com_google_code_gson_gson_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> net_clanwolf_starmap_net_clanwolf_starmap_transfer_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> net_clanwolf_starmap_net_clanwolf_starmap_logging_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_preloader_jar .[#D3D3D3].> org_openjfx_javafx_graphics_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_preloader_jar .[#D3D3D3].> org_openjfx_javafx_controls_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> net_clanwolf_starmap_net_clanwolf_starmap_client_preloader_jar
net_clanwolf_starmap_io_nadron_client_jar .[#D3D3D3].> net_clanwolf_starmap_net_clanwolf_starmap_logging_jar
net_clanwolf_starmap_io_nadron_client_jar -[#000000]-> io_netty_netty_common_jar
io_netty_netty_transport_jar .[#D3D3D3].> io_netty_netty_common_jar
io_netty_netty_transport_jar .[#D3D3D3].> io_netty_netty_buffer_jar
io_netty_netty_resolver_jar .[#D3D3D3].> io_netty_netty_common_jar
io_netty_netty_transport_jar -[#000000]-> io_netty_netty_resolver_jar
net_clanwolf_starmap_io_nadron_client_jar -[#000000]-> io_netty_netty_transport_jar
io_netty_netty_buffer_jar .[#D3D3D3].> io_netty_netty_common_jar
net_clanwolf_starmap_io_nadron_client_jar -[#000000]-> io_netty_netty_buffer_jar
io_netty_netty_codec_jar .[#D3D3D3].> io_netty_netty_common_jar
io_netty_netty_codec_jar .[#D3D3D3].> io_netty_netty_buffer_jar
io_netty_netty_codec_jar .[#D3D3D3].> io_netty_netty_transport_jar
net_clanwolf_starmap_io_nadron_client_jar -[#000000]-> io_netty_netty_codec_jar
io_netty_netty_handler_jar .[#D3D3D3].> io_netty_netty_common_jar
io_netty_netty_handler_jar .[#D3D3D3].> io_netty_netty_resolver_jar
io_netty_netty_handler_jar .[#D3D3D3].> io_netty_netty_buffer_jar
io_netty_netty_handler_jar .[#D3D3D3].> io_netty_netty_transport_jar
io_netty_netty_transport_native_unix_common_jar .[#D3D3D3].> io_netty_netty_common_jar
io_netty_netty_transport_native_unix_common_jar .[#D3D3D3].> io_netty_netty_buffer_jar
io_netty_netty_transport_native_unix_common_jar .[#D3D3D3].> io_netty_netty_transport_jar
io_netty_netty_handler_jar -[#000000]-> io_netty_netty_transport_native_unix_common_jar
io_netty_netty_handler_jar .[#D3D3D3].> io_netty_netty_codec_jar
net_clanwolf_starmap_io_nadron_client_jar -[#000000]-> io_netty_netty_handler_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> net_clanwolf_starmap_io_nadron_client_jar
org_openjfx_javafx_controls_jar -[#000000]-> org_openjfx_javafx_controls_jar_win
org_openjfx_javafx_controls_jar .[#D3D3D3].> org_openjfx_javafx_graphics_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> org_openjfx_javafx_controls_jar
org_openjfx_javafx_graphics_jar -[#000000]-> org_openjfx_javafx_graphics_jar_win
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> org_openjfx_javafx_graphics_jar
org_openjfx_javafx_base_jar -[#000000]-> org_openjfx_javafx_base_jar_win
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> org_openjfx_javafx_base_jar
org_openjfx_javafx_fxml_jar -[#000000]-> org_openjfx_javafx_fxml_jar_win
org_openjfx_javafx_fxml_jar .[#D3D3D3].> org_openjfx_javafx_controls_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> org_openjfx_javafx_fxml_jar
org_openjfx_javafx_web_jar -[#000000]-> org_openjfx_javafx_web_jar_win
org_openjfx_javafx_web_jar .[#D3D3D3].> org_openjfx_javafx_controls_jar
org_openjfx_javafx_web_jar .[#D3D3D3].> org_openjfx_javafx_media_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> org_openjfx_javafx_web_jar
org_openjfx_javafx_media_jar -[#000000]-> org_openjfx_javafx_media_jar_win
org_openjfx_javafx_media_jar .[#D3D3D3].> org_openjfx_javafx_graphics_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> org_openjfx_javafx_media_jar
org_openjfx_javafx_swing_jar -[#000000]-> org_openjfx_javafx_swing_jar_win
org_openjfx_javafx_swing_jar .[#D3D3D3].> org_openjfx_javafx_graphics_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> org_openjfx_javafx_swing_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> org_kynosarges_tektosyne_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> org_apache_commons_commons_collections4_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> commons_net_commons_net_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> org_jetbrains_annotations_jar
org_jitsi_irc_api_jar -[#000000]-> commons_codec_commons_codec_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> org_jitsi_irc_api_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> net_coobird_thumbnailator_jar
net_clanwolf_starmap_net_clanwolf_starmap_client_jar -[#000000]-> com_github_kwhat_jnativehook_jar
@enduml